# Create user and add him to groups
- name: Ensure a 'docker' group
  group:
    name: docker
    state: present

- name: Add a new user
  user:
    name: "{{ user }}"
    shell: /bin/bash
    password: "{{ user_password | password_hash('sha512') }}"
    groups: "docker"

- name: Deploy SSH Key
  authorized_key:
    user: "ec2-user"
    key: "{{ lookup('file', '~/.ssh/master.pub') }}"
    state: present



- name: Update sshd  отмена запрета
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "Match User deploy"
    state: present

- name: Update sshd  отмена запрета
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PasswordAuthentication yes"
    state: present
  notify:
    - Restart sshd

