- name: "run command"
  become: yes
  gather_facts: no
  hosts: all
  tasks:
    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - amazon-linux-extras

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install epel-release
      shell: "amazon-linux-extras install epel -y"

    - name: Ansible Install
      shell: "amazon-linux-extras install ansible2 -y"

    - name: Install sshpass
      yum:
        name: sshpass
        state: present

    - file:
        path: /var/run/docker.sock
        mode: 666



